****************
Acknowledgements
****************

This work was funded in part by the DARPA XDATA program under contract FA8750-12-2-0309. Our DARPA program manager is `Mr. Wade Shen <http://www.darpa.mil/staff/mr-wade-shen>`_ and our XDATA Principal Investigator is `Prof. Haesun Park <http://www.cc.gatech.edu/~hpark/>`_ of the Georgia Institute of Technology. We would like to thank Rundong Du for the dblp ground truth data set and Dr. Ramakrishnan Kannan of ORNL for the MPI-FAUN! distributed code.  Also, special thanks to Dr. Richard Boyd, Dr. Da Kuang, and Ashley Scripka-Beavers for their contributions to previous versions of this documentation and significant technical contributions.
