::

	Barry Drake 
	Research Scientist 
	Information and Communications Laboratory (ICL) 
	Information and Cyber Sciences Directorate (ICSD) 
	Georgia Tech Research Institute (GTRI) 
	75 5TH St. NW STE 900 
	ATLANTA, GA 30308-1018
	barry.drake@gtri.gatech.edu
	
	Stephen Lee-Urban 
	Research Scientist
	Information and Communications Laboratory (ICL)
	Information and Cyber Sciences Directorate (ICSD)
	Georgia Tech Research Institute (GTRI) 
	75 5TH St. NW STE 900 
	ATLANTA, GA 30308-1018
	stephen.lee-urban@gtri.gatech.edu
